# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfb6ebcc88926964430c81a7f5f8dc3f7f5b5d166dfcf5a925222bc63825fed301d8370df326823bcf07c2344016d19df764f6a6be928e53915ce1bc820b141c

test:
  secret_key_base: 5bc343fcf285425892ecc742526bf8345f8076e3bd7e4bd5e3756ca2901f6ade762f31d4472e1daa829920de8dcde3ee3533221da2484200ce2d8f6887aefc7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
