# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a769300df5fadd3fa070f0a529f0be3c0a7882202e17bc2d0ee9e301deb2949cf57c64b6952b6071a9ef07eab23f4282d6747eb203f3dbff945584ae70231f1

test:
  secret_key_base: 6c1dd1116c18ec62154f3c44043c0a66d351b410aba190e044c6adcf88124ac7a31c807f9601560cf8e40b98295c47c7a989c25d580b977c22e78302c1f7a537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
